/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public class InterpsVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public InterpsVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(InterpsVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MorfeuszWrapperJNI.delete_InterpsVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public InterpsVector() {
    this(MorfeuszWrapperJNI.new_InterpsVector(), true);
  }

  public long size() {
    return MorfeuszWrapperJNI.InterpsVector_size(swigCPtr, this);
  }

  public long capacity() {
    return MorfeuszWrapperJNI.InterpsVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    MorfeuszWrapperJNI.InterpsVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return MorfeuszWrapperJNI.InterpsVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    MorfeuszWrapperJNI.InterpsVector_clear(swigCPtr, this);
  }

  public void add(MorphInterpretation x) {
    MorfeuszWrapperJNI.InterpsVector_add(swigCPtr, this, MorphInterpretation.getCPtr(x), x);
  }

  public MorphInterpretation get(int i) {
    return new MorphInterpretation(MorfeuszWrapperJNI.InterpsVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, MorphInterpretation val) {
    MorfeuszWrapperJNI.InterpsVector_set(swigCPtr, this, i, MorphInterpretation.getCPtr(val), val);
  }

}
