/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public class morfeusz {
  public static MorfeuszCharset getDEFAULT_MORFEUSZ_CHARSET() {
    return MorfeuszCharset.swigToEnum(morfeuszJNI.DEFAULT_MORFEUSZ_CHARSET_get());
  }

}
