/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public class Morfeusz {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Morfeusz(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Morfeusz obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MorfeuszWrapperJNI.delete_Morfeusz(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Morfeusz() {
    this(MorfeuszWrapperJNI.new_Morfeusz__SWIG_0(), true);
  }

  public Morfeusz(String filename) {
    this(MorfeuszWrapperJNI.new_Morfeusz__SWIG_1(filename), true);
  }

  public ResultsIterator analyze(String text) {
    return new ResultsIterator(MorfeuszWrapperJNI.Morfeusz_analyze__SWIG_0(swigCPtr, this, text), true);
  }

  public void analyze(String text, InterpsVector result) {
    MorfeuszWrapperJNI.Morfeusz_analyze__SWIG_1(swigCPtr, this, text, InterpsVector.getCPtr(result), result);
  }

  public void setEncoding(MorfeuszCharset encoding) {
    MorfeuszWrapperJNI.Morfeusz_setEncoding(swigCPtr, this, encoding.swigValue());
  }

}
