/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public class MorfeuszWrapperJNI {

  static {
    System.loadLibrary("jmorfeusz");
  }

  public final static native long new_MorfeuszException(String jarg1);
  public final static native void delete_MorfeuszException(long jarg1);
  public final static native String MorfeuszException_what(long jarg1, MorfeuszException jarg1_);
  public final static native long new_Morfeusz__SWIG_0();
  public final static native long new_Morfeusz__SWIG_1(String jarg1);
  public final static native void delete_Morfeusz(long jarg1);
  public final static native long Morfeusz_analyze__SWIG_0(long jarg1, Morfeusz jarg1_, String jarg2);
  public final static native void Morfeusz_analyze__SWIG_1(long jarg1, Morfeusz jarg1_, String jarg2, long jarg3, InterpsVector jarg3_);
  public final static native void Morfeusz_setEncoding(long jarg1, Morfeusz jarg1_, int jarg2);
  public final static native long ResultsIterator_getNext(long jarg1, ResultsIterator jarg1_);
  public final static native boolean ResultsIterator_hasNext(long jarg1, ResultsIterator jarg1_);
  public final static native void delete_ResultsIterator(long jarg1);
  public final static native int MorphInterpretation_getStartNode(long jarg1, MorphInterpretation jarg1_);
  public final static native int MorphInterpretation_getEndNode(long jarg1, MorphInterpretation jarg1_);
  public final static native String MorphInterpretation_getOrth(long jarg1, MorphInterpretation jarg1_);
  public final static native String MorphInterpretation_getLemma(long jarg1, MorphInterpretation jarg1_);
  public final static native int MorphInterpretation_getTagnum(long jarg1, MorphInterpretation jarg1_);
  public final static native int MorphInterpretation_getNamenum(long jarg1, MorphInterpretation jarg1_);
  public final static native String MorphInterpretation_getTag(long jarg1, MorphInterpretation jarg1_);
  public final static native String MorphInterpretation_getName(long jarg1, MorphInterpretation jarg1_);
  public final static native void delete_MorphInterpretation(long jarg1);
  public final static native int DEFAULT_MORFEUSZ_CHARSET_get();
  public final static native long new_InterpsVector();
  public final static native long InterpsVector_size(long jarg1, InterpsVector jarg1_);
  public final static native long InterpsVector_capacity(long jarg1, InterpsVector jarg1_);
  public final static native void InterpsVector_reserve(long jarg1, InterpsVector jarg1_, long jarg2);
  public final static native boolean InterpsVector_isEmpty(long jarg1, InterpsVector jarg1_);
  public final static native void InterpsVector_clear(long jarg1, InterpsVector jarg1_);
  public final static native void InterpsVector_add(long jarg1, InterpsVector jarg1_, long jarg2, MorphInterpretation jarg2_);
  public final static native long InterpsVector_get(long jarg1, InterpsVector jarg1_, int jarg2);
  public final static native void InterpsVector_set(long jarg1, InterpsVector jarg1_, int jarg2, long jarg3, MorphInterpretation jarg3_);
  public final static native void delete_InterpsVector(long jarg1);
}
