/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public enum MorfeuszCharset {
  UTF8,
  ISO8859_2,
  CP1250,
  CP852;

  public final int swigValue() {
    return swigValue;
  }

  public static MorfeuszCharset swigToEnum(int swigValue) {
    MorfeuszCharset[] swigValues = MorfeuszCharset.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MorfeuszCharset swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MorfeuszCharset.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MorfeuszCharset() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MorfeuszCharset(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MorfeuszCharset(MorfeuszCharset swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

