/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public class MorfeuszException {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MorfeuszException(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MorfeuszException obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MorfeuszWrapperJNI.delete_MorfeuszException(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MorfeuszException(String what) {
    this(MorfeuszWrapperJNI.new_MorfeuszException(what), true);
  }

  public String what() {
    return MorfeuszWrapperJNI.MorfeuszException_what(swigCPtr, this);
  }

}
