/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package pl.waw.ipipan.morfeusz;

public class ResultsIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public ResultsIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ResultsIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        MorfeuszWrapperJNI.delete_ResultsIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MorphInterpretation getNext() {
    return new MorphInterpretation(MorfeuszWrapperJNI.ResultsIterator_getNext(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return MorfeuszWrapperJNI.ResultsIterator_hasNext(swigCPtr, this);
  }

}
